### ISSUE TITLE
Migrate app from heroku to amazon web service

### ISSUE THREAD

**Issue by fercreek** [reidmorrison/symmetric-encryption#141]
Hi, we have an application in Heroku and we use PostgreSQL. How can I migrate all my data to AWS RDS and using AWS EC2? There some kind of guide to moving my app?

**Comment by reidmorrison** [comment]
You can move the data in the database without any impact on Symmetric Encryption.
I would recommend doing a key rotation after moving the data and moving to AWS KMS to secure your data encryption key if not already using it.
Another option is to switch to Secret Config and store your data encryption keys in AWS SSM Parameter store, thereby eliminating the need for the `symmetric-encryption.yml` file.
