### ISSUE TITLE
Upgrading v3 to v4 when using rails

### ISSUE THREAD

**Issue by dorongutman** [reidmorrison/symmetric-encryption#147]
I'm using symmetric-encryption version 3.7.1 in rails. We don't call `SymmetricEncryption.decrypt` or `SymmetricEncryption.encrypt` or any direct call to `SymmetricEncryption` at all. We only use it as part of rails' active record with mongoid.

So is it true the only thing I need to do is to make sure the `ciphers` section in the `symmetric-enncryption.yaml` file has `encoding:      :base64strict` (as opposed to to `:base64`), and to add `always_add_header: false`?

**Comment by reidmorrison** [comment]
According to the readme, the defaults have changed, so only set the values if they are not already set in your yaml file. Since encoding is already `:base64` I would not change it. Just add `always_add_header: false`.
