### ISSUE TITLE
Allow data encryption key read from env var for AWS Keystore

### ISSUE THREAD

**Issue by ram-nadella** [reidmorrison/symmetric-encryption#149]
### Environment
* Ruby Version: 2.6
* Symmetric Encryption Version: 4.3.2
* Application/framework names and versions: Rails 6.x
* Keystore: AWS

### Expected Behavior

(not a bug, new feature)

Be able to read the data encryption key from an env var when using the AWS Keystore instead of file to avoid putting keys on the filesystem.

### Actual Behavior

Feature does not exist

### Pull Request

https://github.com/rocketjob/symmetric-encryption/pull/148 (Work in progress)

**Comment by reidmorrison** [comment]
We have switched away from the complex configuration file and now use Secret Config to hold the encryption keys. It also holds all of our passwords and other configuration settings. 
We found it much simpler to manage, and is also secured by a KMS key.
https://config.rocketjob.io/
