### ISSUE TITLE
Validates Uniqueness (discussion)

### ISSUE THREAD

**Issue by mattconnolly** [reidmorrison/symmetric-encryption#38]
Validates uniqueness appears to work, although:

1. You need to validate the encrypted_* field which doesn't match up with form fields for display to user; and
2. shoulda-matcher validates_uniqueness_of(:encrypted_*) doesn't seem to work.

Could this be solved by a custom validator such as "validates :field, :encrypted_uniqueness => true"

Thoughts?

**Comment by reidmorrison** [comment]
If this is still needed, please send a Pull Request with the necessary features.
