### ISSUE TITLE
Beating the railtie config.before_configuration

### ISSUE THREAD

**Issue by dradford** [reidmorrison/symmetric-encryption#43]
Hi Reid,

More of a discussion than an issue.

I'm running the symmetric-encryption gem in a rails app. I have the same app running on three different heroku applications for production, development and staging. On Heroku, these all have to run under the production rails environment. I want to use different keys in each application, but because they're all running under rails_env=production, they all load the same RSA key.

I've had a look in the gem code to find the best place to override this and I'm struggling. When I try to load the SymmetricEncryption cipher in application.rb based on an environment variable, the gem's railtie before_configuration has already been run. My code in application.rb is like this:

    ::SymmetricEncryption.load!("#{Rails.root}/config/symmetric-encryption.yml", "custom_environment") 
    config.symmetric_encryption.cipher = ::SymmetricEncryption.cipher

and I get the error (wrong key): OpenSSL::PKey::RSAError: padding check failed

My only other thoughts are either:

1. build a shim containing a railtie with a config.before_configuration and mess with the load order until the shim loads first

2. fork the repo and adjust this gem's railtie to test for an environment variable first

    ::SymmetricEncryption.load!(config_file, SYMMETRY_ENVIRONMENT  || Rails.env)

I'm probably missing something here, any suggestions would be hugely appreciated.

Thanks,
Damien

**Comment by reidmorrison** [comment]
Documentation updated
