### ISSUE TITLE
Regular expression search on encrypted fields.

### ISSUE THREAD

**Issue by delneet** [reidmorrison/symmetric-encryption#45]
I have a model with field ```:last_name``` that (amongst others) needs to be encrypted. However.
I currently have a autocomplete search on this field that uses a regular expression.
```ruby
def autocomplete_user_last_name
    term = params[:term]
    search = '.*' + Regexp.escape(term) + '.*'
    items = User.where(last_name: /#{search}/i).in(roles: [:user])
    render json: json_for_autocomplete(items, :full_name)
end
```
Is there any way I can reproduce this autocompletion behaviour with encrypted fields?

**Comment by reidmorrison** [comment]
Unfortunately by its very need for complete privacy with encrypted data, autocomplete on encrypted fields does not appear possible.
