### ISSUE TITLE
Support for serialize

### ISSUE THREAD

**Issue by traxanos** [reidmorrison/symmetric-encryption#48]
Hi it's possible to get support for serialize? At the moment i've got an error:

```
Coercible::UnsupportedCoercion: Coercible::Coercer::Hash#to_string doesn't know how to coerce {:test=>1}
```

**Comment by reidmorrison** [comment]
In order to support non-string types, see the documentation for your framework:
http://reidmorrison.github.io/symmetric-encryption/frameworks.html

**Comment by traxanos** [comment]
hi

i know the type :json. i use it as workaround. the deserilized hash is still frozen, so i can only insert a new hash.

```
  attr_encrypted :payment_data, type: :json
  def update_payment_data_field(key, value)
    x = payment_data.dup
    x[key.to_s] = value
    self.payment_data = x
  end
```

**Comment by barnett** [comment]
@reidmorrison that link is dead, is there a updated one?

**Comment by bpardee** [comment]
http://rocketjob.github.io/symmetric-encryption/frameworks.html

**Comment by barnett** [comment]
Thanks @bpardee
