### ISSUE TITLE
NameError: uninitialized constant SymmetricEncryption

### ISSUE THREAD

**Issue by TyMac** [reidmorrison/symmetric-encryption#50]
I am trying to simply use symmetric-encryption using in non-Rails environments following the documentation here: 

http://reidmorrison.github.io/symmetric-encryption/configuration.html

I am getting the following errors however:

[root@Ruby]# irb
1.9.3-p551 :001 > SymmetricEncryption.load!('/home/user/Documents/Dev/Scripts/Ruby/symmetric-encryption.yml', 'production')
NameError: uninitialized constant SymmetricEncryption
	from (irb):1
	from /usr/local/rvm/rubies/ruby-1.9.3-p551/bin/irb:12:in `<main>'
1.9.3-p551 :002 > SymmetricEncryption.encrypt "Sensitive data"
NameError: uninitialized constant SymmetricEncryption
	from (irb):2
	from /usr/local/rvm/rubies/ruby-1.9.3-p551/bin/irb:12:in `<main>'

I am using ruby 1.9.3 - I had no rails environment set up - but then after installing rails and running:

SymmetricEncryption.generate_symmetric_key_files('/home/user/Documents/Dev/Scripts/Ruby/symmetric-encryption.yml', 'production')

I am good:

1.9.3-p551 :001 > require 'symmetric-encryption' => true 
1.9.3-p551 :002 > SymmetricEncryption.load!('/home/user/Documents/Dev/Scripts/Ruby/symmetric-encryption.yml', 'production')

Symmetric Encryption key file: '/etc/rails/.rails_old.key' not found or readable.
To generate the keys for the first time run: rails generate symmetric_encryption:new_keys

 => true 
1.9.3-p551 :003 > SymmetricEncryption.encrypt "Sensitive data" => "djmbOB+CSL+wcjXcD1gEQ==" 

Do I have to set up rails in order for this to work even in a "non-Rails" environment?

**Comment by reidmorrison** [comment]
Look under the section named [Using in non-Rails environments](http://reidmorrison.github.io/symmetric-encryption/configuration.html). It describes how to run Symmetric Encryption without rails, as well as how to generate the necessary key files to run it for the first time.

Just remember to edit the `symmetric-encryption.yml` file with the location of where to generate the key files for your production environment. 

It may be easier to read the Rails instructions first as they are more detailed, and then follow the non-rails setup.

To skip the configuration file, and for development only use, you could run the following to get comfortable with Symmetric Encryption ( for testing purposes only ):

```ruby
require 'symmetric-encryption'
# Test cipher
SymmetricEncryption.cipher = SymmetricEncryption::Cipher.new(
  cipher_name: 'aes-128-cbc',
  key:         '1234567890ABCDEF1234567890ABCDEF',
  iv:          '1234567890ABCDEF',
  encoding:    :base64strict
)

encrypted = SymmetricEncryption.encrypt 'Hello World'

SymmetricEncryption.decrypt(encrypted)
```

**Comment by reidmorrison** [comment]
Updated documentation for Standalone configuration:
http://reidmorrison.github.io/symmetric-encryption/standalone.html
