### ISSUE TITLE
Conflict with attr_encrypted gem

### ISSUE THREAD

**Issue by mnipper** [reidmorrison/symmetric-encryption#51]
When running in rails development mode and also including the attr_encrypted gem, I get the following error each time an ActiveRecord model is instantiated:

```
2015-09-28 17:18:25.837 [INFO] Completed 500 Internal Server Error in 53.2ms (pid:4098)                                                                                            
2015-09-28 17:18:25.837 [FATAL] SystemStackError (stack level too deep):
  actionpack (3.2.18) lib/action_dispatch/middleware/reloader.rb:70 (pid:4098)
```

Rails version: 3.2.18
attr_encrypted version: 1.3.2
symmetric-encryption version: 3.7.2

Loading symmetric-encryption before `ActiveRecord::Base` is loaded (and therefore not loading your ActiveRecord::Base extension) avoids this problem.

It also seems the api of your attr_encrypted doesn't match the current api of the attr_encrypted gem in places, so it is not currently a "drop-in replacement" as described in the documentation.

Would you be willing to make the exclusion of your attr_encrypted extension an option to avoid conflicts with the attr_encrypted gem?

**Comment by reidmorrison** [comment]
You can't run both `attr_encrypted` and `symmetric-encryption` gems at the same time. After adding `symmetric-encryption` remove the `attr_encrypted` gem.

When we moved from `attr_encrypted` to `symmetric-encryption` we implemented the common API's in  `attr_encrypted` at that time. Which  `attr_encrypted` API's do you need?

**Comment by mnipper** [comment]
Specifically, I'd like the option to have an individual key for each attribute.  The attr_encrypted gem accomplishes this by taking a key attribute in the options hash.

I think perhaps the larger issue is that as time goes on there will likely be more divergence between the attr_encrypted gem and the implementation of attr_encrypted in symmetric-encryption.  It would be nice to allow people to use both gems together by including an optional configuration option to not include the symmetric-encryption version of attr_encrypted if desired, which is why I asked about the possibility of you considering that.

**Comment by reidmorrison** [comment]
`attr_encrypted` and `symmetric-encryption` are actually trying to do very different things. The focus with `symmetric-encryption` is on meeting compliance requirements and audits. `attr_encrypted` leaves the securing of encryption keys up to you and allows the keys to be stored in the source code itself which is insecure, and a compliance violation.

When we moved from `attr_encrypted` to `symmetric-encryption` it was not necessary to re-encrypt all the data from the outset, `OpenSSL` has an API to take the pass-phrase that is input into `attr_encrypted` and extract the key and IV from it. If you look inside `attr_encrypted` you should be able to find that code. I.e. One can switch from `attr_encrypted` to `symmetric-encryption` with `symmetric-encryption` decrypting existing `attr_encrypted` data.

A possible option to support multiple keys would be allow the attr_encrypted api in `symmetric-encryption` to take a `version` option that would specify the key version to use to encrypt and decrypt data for that attribute:

```ruby
class Sample < ActiveRecord::Base
  attr_encrypted :important, version: 2
end
```

And then in the `symmetric-encryption.yml` file we could add multiple keys ( versions ) to match each hard coded version in the model. 

Understanding the compliance implications, if you still want to disable the `attr_encrypted` in `symmetric-encryption` when `attr_encrypted` is already loaded I could make the following change in `symmetric_encryption.rb`:

```ruby
if defined?(ActiveRecord::Base) && !defined?(AttrEncrypted::Version)
  require 'symmetric_encryption/extensions/active_record/base'
end
```

As long as the `attr_encrypted` gem is listed in the Gemfile before `symmetric-encryption`, then `symmetric-encryption` will not load it's own `attr_encrypted` extensions for ActiveRecord.

**Comment by mnipper** [comment]
I can certainly understand your apprehension in including a key option per attribute as `attr_encrypted` does (my plan is to manage those keys with `symmetric-encryption`).  I think my preference would be for option 2 above (only require the active record extension if `AttrEncrypted::Version` is not defined).

Thank you for your prompt and thorough responses!
