### ISSUE TITLE
How to encrypt fields when bulk creating through db.collection.insert()

### ISSUE THREAD

**Issue by ChristofferJoergensen** [reidmorrison/symmetric-encryption#52]
Thanks for making this Gem available!

In many cases I do not use the Mongoid create action, but instead I bulk create through the mongo Shell method [db.collection.insert()](http://docs.mongodb.org/v2.4/reference/method/db.collection.insert/). When doing so my `encrypted_xx` becomes `nil`, instead of the intended field value.

Is there a workaround I can apply?

**Comment by reidmorrison** [comment]
Correct, the encryption is occurring in your Ruby code/models. Going directly into the database and running commands there bypasses the encryption code. The same would apply with relational databases such as MySQL and Postgres.

If you call the insert method directly from your Rails console you can manually encrypt the value using `SymmetricEncryption.encrypt('value')` and put the result in your encrypted column as part of you batch insert.

**Comment by ChristofferJoergensen** [comment]
OK, if that doesn't circumvent any steps taken to ensure database-compatible encoding I'm happy. Thanks for your quick answer :-)
